### ISSUE TITLE
add vanila nix. Avoid flake

### ISSUE THREAD

**Issue by IVKLD** [MatthewCash/asus-wmi-screenpad-module#1]
https://codefile.io/f/CKQc7oiwV5

```
let asus-wmi-screenpad-module = import ./mods/asus-screenpad-module/asus-screenpad.nix { lib = pkgs.lib; pkgs = pkgs;};
in
{
boot.kernelPackages = pkgs.linuxPackages_6_9;
boot.kernelModules = ["asus_wmi_screenpad"];
boot.extraModulePackages = with config.boot.kernelPackages;
    [ asus-wmi-screenpad-module.defaultPackage];
}
```
I hate flake and don't want to use it in general in places where plain vanilla nixos can handle without the tambourine dance.

**Comment by MatthewCash** [comment]
I just added flake-compat in bb221bd6ecc4f0ab1920ccf1663e237d419fc26f so you should now be able to use the module by importing `default.nix`.

**Comment by IVKLD** [comment]
If it's not too much trouble, can you explain in more detail how to install it? I've been using nixos for 2 months and have been building my packages for 2 weeks. So I don't have much experience.

**Comment by MatthewCash** [comment]
It will depend on how you manage your dependencies, if have this repo set up as a channel, you should be able to import it like this.

```nix
let
    linux = pkgs.linuxPackages_6_9;
    asus-wmi-screenpad = (import <asus-wmi-screenpad-module>).defaultPackage."${system}".override linux.kernel;
in
{
boot.kernelPackages = linux;
boot.kernelModules = ["asus_wmi_screenpad"];
boot.extraModulePackages = with config.boot.kernelPackages;
    [ asus-wmi-screenpad ];
}
```

**Comment by IVKLD** [comment]
thx
